<?php
/**
 * Application level Controller
 *
 * This file is application-wide controller file. You can put all
 * application-wide controller-related methods here.
 *
 * PHP 5
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       app.Controller
 * @since         CakePHP(tm) v 0.2.9
 * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
require_once(APP.'Vendor'.'/facebook/facebook.php');
require_once(APP.'Vendor'.'/twitteroauth/twitteroauth.php');
App::uses('Controller', 'Controller');

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @package       app.Controller
 * @link http://book.cakephp.org/2.0/en/controllers.html#the-app-controller
 */
class AppController extends Controller {
	public $helpers = array('Session', 'Html', 'Form');
	public $facebookConfig = array('appId' => '395499187171209',
								   'secret' => 'fdae1ccd80611c03ed5043e039d2838e',
								   'fileUpload' => false);
	public $facebookAppUrl = "https://apps.facebook.com/cakeapppctroll";
	public $twitterConfig = array('key'    => 'amnm5E6IcQtBuofeME31sQ',
	                              'secret' => 'M59PU82xtP9p4KLIUj8CaZtqL2qeG3q75aqB8IdM');
	public $operators = array('58412' =>'0412',
							  '0414'  =>'0414',
							  '0424'  =>'0424',
							  '158'   =>'0416',
							  '199'   =>'0426');
	public $countries = array( 
        ''=>'Selecciona un país',
		've'=>'Venezuela',
		'af'=>'Afganistán',
		'al'=>'Albania',
		'de'=>'Alemania',
		'ad'=>'Andorra',
		'ao'=>'Angola',
		'ai'=>'Anguila',
		'aq'=>'Antártica',
		'ag'=>'Antigua y Barbuda',
		'an'=>'Antillas Holandesas',
		'sa'=>'Arabia Saudá',
		'dz'=>'Argelia',
		'ar'=>'Argentina',
		'am'=>'Armenia',
		'aw'=>'Aruba',
		'au'=>'Australia',
		'at'=>'Austria',
		'az'=>'Azerbaiján',
		'be'=>'Bélgica',
		'bs'=>'Bahamas',
		'bh'=>'Bahrain',
		'bd'=>'Bangladesh',
		'bb'=>'Barbados',
		'by'=>'Belarus',
		'bz'=>'Belice',
		'bj'=>'Benin',
		'bm'=>'Bermuda',
		'bo'=>'Bolivia',
		'ba'=>'Bosnia-Hercegovina',
		'bw'=>'Botswana',
		'br'=>'Brasil',
		'bn'=>'Brunei Darussalam',
		'bg'=>'Bulgaria',
		'bf'=>'Burkina Faso',
		'bi'=>'Burundi',
		'bt'=>'Bután',
		'cv'=>'Cabo Verde',
		'kh'=>'Camboya',
		'cm'=>'Camerún',
		'ca'=>'Canadá',
		'td'=>'Chad',
		'cl'=>'Chile',
		'cn'=>'China',
		'cy'=>'Chipre',
		'va'=>'Ciudad del Vaticano',
		'co'=>'Colombia',
		'km'=>'Comoras',
		'cg'=>'Congo',
		'kp'=>'Corea del Norte',
		'kr'=>'Corea del Sur',
		'ci'=>'Costa de Marfil',
		'cr'=>'Costa Rica',
		'hr'=>'Croacia',
		'cu'=>'Cuba',
		'dk'=>'Dinamarca',
		'dj'=>'Djibuti',
		'dm'=>'Dominica',
		'ec'=>'Ecuador',
		'eg'=>'Egipto',
		'sv'=>'El Salvador',
		'ae'=>'Emiratos Árabes Unidos',
		'er'=>'Eritrea',
		'sk'=>'Eslovaquia',
		'si'=>'Eslovenia',
		'sp'=>'España',
		'ee'=>'Estonia',
		'et'=>'Etiopía',
		'ru'=>'Federación Rusa',
		'fj'=>'Fiji',
		'ph'=>'Filipinas',
		'fi'=>'Finlandia',
		'fr'=>'Francia',
		'fx'=>'Francia Metropolitana',
		'ga'=>'Gabón',
		'gm'=>'Gambia',
		'ge'=>'Georgia',
		'gs'=>'Georgia del Sur e Islas Sandwich del Sur',
		'gh'=>'Ghana',
		'gi'=>'Gibraltar',
		'gr'=>'Grecia',
		'gl'=>'Groenlandia',
		'gp'=>'Guadalupe',
		'gu'=>'Guam',
		'gt'=>'Guatemala',
		'gf'=>'Guayana Francesa',
		'gn'=>'Guinea',
		'gq'=>'Guinea Ecuatorial',
		'gw'=>'Guinea-Bissau',
		'gy'=>'Guyana',
		'ht'=>'Haití',
		'hn'=>'Honduras',
		'hk'=>'Hong Kong',
		'hu'=>'Hungría',
		'in'=>'India',
		'id'=>'Indonesia',
		'ir'=>'Irán',
		'iq'=>'Irak',
		'ie'=>'Irlanda',
		'bv'=>'Isla Bouvet',
		'cx'=>'Isla Christmas',
		'nf'=>'Isla Norfolk',
		'is'=>'Islandia',
		'ky'=>'Islas Caimanes',
		'cc'=>'Islas Cocos (Keeling)',
		'ck'=>'Islas Cook',
		'fo'=>'Islas Faroe',
		'hm'=>'Islas Heard y Mc Donald',
		'fk'=>'Islas Malvinas',
		'mp'=>'Islas Marianas Septentrionales',
		'mh'=>'Islas Marshall',
		'sb'=>'Islas Salomón',
		'sj'=>'Islas Svalbard y Jan Mayen',
		'tc'=>'Islas Turks y Caicos',
		'vg'=>'Islas Vírgenes (Británicas)',
		'vi'=>'Islas Vírgenes (EEUU)',
		'wf'=>'Islas Wallis y Futuna',
		'il'=>'Israel',
		'it'=>'Italia',
		'jm'=>'Jamaica',
		'jp'=>'Japón',
		'jo'=>'Jordania',
		'qa'=>'Katar',
		'kz'=>'Kazajistán',
		'ke'=>'Kenia',
		'kg'=>'Kirguizistán',
		'ki'=>'Kiribati',
		'kw'=>'Kuwait',
		'lb'=>'Líbano',
		'la'=>'Laos, República Popular',
		'ls'=>'Lesoto',
		'lv'=>'Letonia',
		'lr'=>'Liberia',
		'ly'=>'Libia',
		'li'=>'Liechtenstein',
		'lt'=>'Lituania',
		'lu'=>'Luxemburgo',
		'mx'=>'México',
		'mc'=>'Mónaco',
		'mo'=>'Macao',
		'mk'=>'Macedonia',
		'mg'=>'Madagascar',
		'my'=>'Malasia',
		'mw'=>'Malaui',
		'mv'=>'Maldivas',
		'ml'=>'Mali',
		'mt'=>'Malta',
		'ma'=>'Marruecos',
		'mq'=>'Martinica',
		'mu'=>'Mauricio',
		'mr'=>'Mauritania',
		'yt'=>'Mayotte',
		'fm'=>'Micronesia',
		'md'=>'Moldova',
		'mn'=>'Mongolia',
		'ms'=>'Montserrat',
		'mz'=>'Mozambique',
		'mm'=>'Myanmar',
		'ne'=>'Níger',
		'na'=>'Namibia',
		'nr'=>'Nauru',
		'np'=>'Nepal',
		'ni'=>'Nicaragua',
		'ng'=>'Nigeria',
		'nu'=>'Niue',
		'no'=>'Noruega',
		'nc'=>'Nueva Caledonia',
		'nz'=>'Nueva Zelanda',
		'om'=>'Omán',
		'nl'=>'Países Bajos',
		'pk'=>'Pakistán',
		'pw'=>'Palau',
		'pa'=>'Panamá',
		'pg'=>'Papua Nueva Guinea',
		'py'=>'Paraguay',
		'pe'=>'Perú',
		'pn'=>'Pitcairn',
		'pf'=>'Polinesia Francesa',
		'pl'=>'Polonia',
		'pt'=>'Portugal',
		'pr'=>'Puerto Rico',
		'gb'=>'Reino Unido',
		'sy'=>'República Árabe de Siria',
		'cf'=>'República Centroafricana',
		'cz'=>'República Checa',
		'do'=>'República Dominicana',
		're'=>'Reunión',
		'rw'=>'Ruanda',
		'ro'=>'Rumanía',
		'eh'=>'Sahara Occidental',
		'ws'=>'Samoa',
		'as'=>'Samoa Americana',
		'kn'=>'San Cristóbal y Nevis',
		'sm'=>'San Marino',
		'vc'=>'San Vicente y las Granadinas',
		'sh'=>'Santa Elena',
		'lc'=>'Santa Lucía',
		'st'=>'Santo Tomé y Príncipe',
		'sn'=>'Senegal',
		'yu'=>'Serbia y Montenegro',
		'sc'=>'Seychelles',
		'sl'=>'Sierra Leona',
		'sg'=>'Singapur',
		'so'=>'Somalía',
		'lk'=>'Sri Lanka',
		'pm'=>'St Pierre y Miquelon',
		'sz'=>'Suazilandia',
		'za'=>'Sudáfrica',
		'sd'=>'Sudán',
		'se'=>'Suecia',
		'ch'=>'Suiza',
		'sr'=>'Surinam',
		'tn'=>'Túnez',
		'th'=>'Tailandia',
		'tw'=>'Taiwan',
		'tz'=>'Tanzanía',
		'tj'=>'Tayiquistán',
		'tf'=>'Territorios australes y antárticos franceses',
		'io'=>'Territorios Británicos del Océano Índico',
		'tp'=>'Timor Oriental',
		'tg'=>'Togo',
		'tk'=>'Tokelau',
		'to'=>'Tonga',
		'tt'=>'Trinidad y Tobago',
		'tm'=>'Turkmenistán',
		'tr'=>'Turquía',
		'tv'=>'Tuvalu',
		'ua'=>'Ucrania',
		'ug'=>'Uganda',
		'uy'=>'Uruguay',
		'us'=>'USA',
		'uz'=>'Uzbekistán',
		'vu'=>'Vanuatu',
		'vn'=>'Vietnam',
		'ye'=>'Yemen',
		'zr'=>'Zaire',
		'zm'=>'Zambia',
		'zw'=>'Zimbabue'
    ); 
}
